# Generated by Django 5.2.4 on 2025-08-03 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("604ac274-4864-47ea-bf11-5179217c9e03"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
