# Generated by Django 5.2.4 on 2025-08-03 19:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_alter_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("0e570034-d621-41e9-801a-a1e03897143a"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
